# Generated by Django 4.1.3 on 2023-01-27 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='booking_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, default=None, max_length=200)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200)),
                ('location', models.CharField(blank=True, default=None, max_length=200)),
                ('lattitude', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=8)),
                ('longitude', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=8)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_type', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('page', models.CharField(blank=True, max_length=200, null=True)),
                ('path', models.FilePathField(path=None)),
                ('body', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200)),
                ('location', models.CharField(blank=True, default=None, max_length=200)),
                ('lattitude', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=8)),
                ('longitude', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=8)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=50, null=True)),
                ('c_type', models.IntegerField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, max_length=50, null=True)),
                ('amount_type', models.CharField(blank=True, max_length=50, null=True)),
                ('usage_limit', models.IntegerField(blank=True, null=True)),
                ('used_by', models.IntegerField(blank=True, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('expiry', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='coupon_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('label', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('pwd', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=50, null=True)),
                ('last_name', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('cust_type', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='customer_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='destination_area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200)),
                ('place', models.CharField(blank=True, default=None, max_length=100)),
                ('country', models.CharField(blank=True, default=None, max_length=100)),
                ('state', models.CharField(blank=True, default=None, max_length=100)),
                ('lattitude', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=8)),
                ('longitude', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=8)),
                ('status', models.BooleanField()),
                ('c_user', models.CharField(blank=True, default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='destination_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=50)),
                ('description', models.CharField(blank=True, default=None, max_length=200)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='destinstions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100)),
                ('address', models.CharField(blank=True, default=None, max_length=200)),
                ('description', models.TextField()),
                ('culture', models.TextField()),
                ('climate', models.TextField()),
                ('lattitude', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=8)),
                ('longitude', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=8)),
                ('status', models.BooleanField(default=False)),
                ('d_area', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.destination_area')),
            ],
        ),
        migrations.CreateModel(
            name='destn_facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default=None, max_length=100)),
                ('description', models.CharField(blank=True, default=None, max_length=200)),
                ('types', models.CharField(blank=True, default=None, max_length=100)),
                ('lattitude', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=8)),
                ('longitude', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=8)),
                ('amount', models.FloatField(blank=True, default=None)),
                ('status', models.BooleanField(default=False)),
                ('destinstions', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.destinstions')),
            ],
        ),
        migrations.CreateModel(
            name='facility_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='faq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('access', models.CharField(blank=True, max_length=200, null=True)),
                ('access_count', models.CharField(blank=True, max_length=200, null=True)),
                ('likes', models.CharField(blank=True, max_length=200, null=True)),
                ('dislike', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='faq_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
                ('popularity', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='hotel_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(blank=True, default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('org_type', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('proof', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(default=True)),
                ('c_user', models.CharField(blank=True, default=None, max_length=100)),
                ('city', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.city')),
                ('destinstion', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.destinstions')),
            ],
        ),
        migrations.CreateModel(
            name='staff_department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('hotel_type', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.organization')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200)),
                ('location', models.CharField(blank=True, default=None, max_length=200)),
                ('lattitude', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=8)),
                ('longitude', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=8)),
                ('status', models.BooleanField(default=False)),
                ('country_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.country')),
            ],
        ),
        migrations.CreateModel(
            name='organization_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='images/')),
                ('organization', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.organization')),
            ],
        ),
        migrations.AddField(
            model_name='organization',
            name='state',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.state'),
        ),
        migrations.CreateModel(
            name='facility_price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(blank=True, default=None)),
                ('discount', models.FloatField(blank=True, default=None)),
                ('total', models.FloatField(blank=True, default=None)),
                ('status', models.BooleanField(default=False)),
                ('dstn_facility', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.destinstions')),
            ],
        ),
        migrations.CreateModel(
            name='facility_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagetype', models.CharField(blank=True, default=None, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('status', models.BooleanField(default=False)),
                ('destinstion', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.destinstions')),
                ('facility', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.destn_facility')),
            ],
        ),
        migrations.CreateModel(
            name='destn_geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(blank=True, default=None, max_length=100)),
                ('title', models.CharField(blank=True, default=None, max_length=100)),
                ('description', models.CharField(blank=True, default=None, max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('destinstions', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.destinstions')),
            ],
        ),
        migrations.AddField(
            model_name='destn_facility',
            name='orgatn',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.organization'),
        ),
        migrations.CreateModel(
            name='destination_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('destinstions', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.destinstions')),
            ],
        ),
        migrations.CreateModel(
            name='customer_auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens', models.CharField(default='', max_length=100)),
                ('username', models.CharField(default='', max_length=50)),
                ('u_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='cust_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=50, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(default=False)),
                ('cust', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.customer')),
            ],
        ),
        migrations.CreateModel(
            name='content_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('overlay', models.CharField(blank=True, max_length=200, null=True)),
                ('weight', models.IntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('cid', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.content')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.state'),
        ),
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('bking_type', models.CharField(blank=True, max_length=50, null=True)),
                ('bk_from', models.CharField(blank=True, max_length=50, null=True)),
                ('bk_to', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('cust', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.customer')),
            ],
        ),
    ]
