# Generated by Django 4.1.3 on 2023-01-24 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200)),
                ('location', models.CharField(blank=True, default=None, max_length=200)),
                ('lattitude', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=8)),
                ('longitude', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=8)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200)),
                ('location', models.CharField(blank=True, default=None, max_length=200)),
                ('lattitude', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=8)),
                ('longitude', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=8)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='destination_area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200)),
                ('place', models.CharField(blank=True, default=None, max_length=100)),
                ('country', models.CharField(blank=True, default=None, max_length=100)),
                ('state', models.CharField(blank=True, default=None, max_length=100)),
                ('lattitude', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=8)),
                ('longitude', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=8)),
                ('status', models.BooleanField()),
                ('c_user', models.CharField(blank=True, default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='destination_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=50)),
                ('description', models.CharField(blank=True, default=None, max_length=200)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='destinstions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100)),
                ('address', models.CharField(blank=True, default=None, max_length=200)),
                ('description', models.TextField()),
                ('culture', models.TextField()),
                ('climate', models.TextField()),
                ('lattitude', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=8)),
                ('longitude', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=8)),
                ('status', models.BooleanField(default=False)),
                ('c_user', models.CharField(blank=True, default=None, max_length=100)),
                ('d_area', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.destination_area')),
            ],
        ),
        migrations.CreateModel(
            name='hotel_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(blank=True, default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200)),
                ('location', models.CharField(blank=True, default=None, max_length=200)),
                ('lattitude', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=8)),
                ('longitude', models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=8)),
                ('status', models.BooleanField(default=False)),
                ('country_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.country')),
            ],
        ),
        migrations.CreateModel(
            name='organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('org_type', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('proof', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(default=True)),
                ('c_user', models.CharField(blank=True, default=None, max_length=100)),
                ('city', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.city')),
                ('destinstion', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.destinstions')),
                ('state', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.state')),
            ],
        ),
        migrations.CreateModel(
            name='destn_geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(blank=True, default=None, max_length=100)),
                ('title', models.CharField(blank=True, default=None, max_length=100)),
                ('description', models.CharField(blank=True, default=None, max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('destinstions', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.destinstions')),
            ],
        ),
        migrations.CreateModel(
            name='destination_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('destinstions', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.destinstions')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state_id',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.state'),
        ),
    ]
