# Generated by Django 4.1.3 on 2023-01-12 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='destination_area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200)),
                ('place', models.CharField(blank=True, default=None, max_length=100)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='destinstions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=100)),
                ('address', models.CharField(blank=True, default=None, max_length=200)),
                ('description', models.TextField()),
                ('climate', models.TextField()),
                ('culture', models.TextField()),
                ('status', models.BooleanField(default=False)),
                ('d_area', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.destination_area')),
            ],
        ),
        migrations.CreateModel(
            name='destn_geography',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('types', models.CharField(blank=True, default=None, max_length=100)),
                ('title', models.CharField(blank=True, default=None, max_length=100)),
                ('description', models.CharField(blank=True, default=None, max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('destinstions', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.destinstions')),
            ],
        ),
        migrations.CreateModel(
            name='destination_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('destinstions', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.destinstions')),
            ],
        ),
    ]
