# Generated by Django 4.1.3 on 2023-01-13 05:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dot_app', '0002_facility_price_destn_facility'),
    ]

    operations = [
        migrations.CreateModel(
            name='organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('org_type', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_person', models.CharField(blank=True, max_length=200, null=True)),
                ('contact_number', models.CharField(blank=True, max_length=200, null=True)),
                ('website', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('proof', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(default=False)),
                ('destinstion', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.destinstions')),
                ('facility', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.destn_facility')),
            ],
        ),
        migrations.CreateModel(
            name='userprofile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.CharField(blank=True, max_length=200, null=True)),
                ('phone', models.CharField(blank=True, max_length=200, null=True)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
                ('status', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.organization')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='organization_images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.ImageField(blank=True, upload_to='images/')),
                ('organization', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.organization')),
            ],
        ),
        migrations.CreateModel(
            name='facility_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagetype', models.CharField(blank=True, default=None, max_length=200)),
                ('image', models.ImageField(blank=True, upload_to='images/')),
                ('status', models.BooleanField(default=False)),
                ('destinstion', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.destinstions')),
                ('facility', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.destn_facility')),
            ],
        ),
    ]
