# Generated by Django 4.1.3 on 2023-01-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0003_organization_userprofile_organization_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination_area',
            name='status',
            field=models.BooleanField(default='0'),
        ),
    ]
