# Generated by Django 4.1.3 on 2023-01-24 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0003_destn_facility_orgatn_facility_image_imagetype_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='cust',
        ),
        migrations.DeleteModel(
            name='booking_type',
        ),
        migrations.DeleteModel(
            name='coupon',
        ),
        migrations.DeleteModel(
            name='coupon_type',
        ),
        migrations.DeleteModel(
            name='booking',
        ),
    ]
