# Generated by Django 4.1.3 on 2023-01-24 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0004_remove_booking_cust_delete_booking_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content_images',
            name='cid',
        ),
        migrations.RemoveField(
            model_name='cust_profile',
            name='cust',
        ),
        migrations.DeleteModel(
            name='customer_type',
        ),
        migrations.DeleteModel(
            name='faq',
        ),
        migrations.DeleteModel(
            name='faq_category',
        ),
        migrations.DeleteModel(
            name='content',
        ),
        migrations.DeleteModel(
            name='content_images',
        ),
        migrations.DeleteModel(
            name='cust_profile',
        ),
        migrations.DeleteModel(
            name='customer',
        ),
    ]
