# Generated by Django 4.1.3 on 2023-01-13 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0004_alter_destination_area_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination_area',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
