# Generated by Django 4.1.3 on 2023-01-27 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0006_booking_type_content_coupon_coupon_type_customer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility_price',
            name='title',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
