# Generated by Django 4.1.3 on 2023-01-16 07:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0007_alter_destination_area_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200)),
                ('location', models.CharField(blank=True, default=None, max_length=200)),
                ('lattitude', models.CharField(blank=True, default=None, max_length=200)),
                ('longitude', models.CharField(blank=True, default=None, max_length=200)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='destination_area',
            name='lattitude',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='destination_area',
            name='longitude',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='destinstions',
            name='lattitude',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='destinstions',
            name='longitude',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='destn_facility',
            name='lattitude',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='destn_facility',
            name='longitude',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.CreateModel(
            name='state',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200)),
                ('location', models.CharField(blank=True, default=None, max_length=200)),
                ('lattitude', models.CharField(blank=True, default=None, max_length=200)),
                ('longitude', models.CharField(blank=True, default=None, max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('country_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.country')),
            ],
        ),
        migrations.CreateModel(
            name='city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200)),
                ('location', models.CharField(blank=True, default=None, max_length=200)),
                ('lattitude', models.CharField(blank=True, default=None, max_length=200)),
                ('longitude', models.CharField(blank=True, default=None, max_length=200)),
                ('status', models.BooleanField(default=False)),
                ('state_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.state')),
            ],
        ),
    ]
