# Generated by Django 4.1.3 on 2023-01-27 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0007_facility_price_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='destn_facility',
            name='lattitude',
        ),
        migrations.RemoveField(
            model_name='destn_facility',
            name='longitude',
        ),
    ]
