# Generated by Django 4.1.3 on 2023-01-16 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0008_country_destination_area_lattitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='lattitude',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=8),
        ),
        migrations.AlterField(
            model_name='city',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=8),
        ),
        migrations.AlterField(
            model_name='country',
            name='lattitude',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=8),
        ),
        migrations.AlterField(
            model_name='country',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=8),
        ),
        migrations.AlterField(
            model_name='destination_area',
            name='lattitude',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=8),
        ),
        migrations.AlterField(
            model_name='destination_area',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=8),
        ),
        migrations.AlterField(
            model_name='destinstions',
            name='lattitude',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=8),
        ),
        migrations.AlterField(
            model_name='destinstions',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=8),
        ),
        migrations.AlterField(
            model_name='destn_facility',
            name='lattitude',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=8),
        ),
        migrations.AlterField(
            model_name='destn_facility',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=8),
        ),
        migrations.AlterField(
            model_name='state',
            name='lattitude',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=8),
        ),
        migrations.AlterField(
            model_name='state',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=3, default=None, max_digits=8),
        ),
    ]
