# Generated by Django 4.1.3 on 2023-01-17 07:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0009_booking_type_content_coupon_coupon_type_customer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='facility',
        ),
        migrations.AddField(
            model_name='destn_facility',
            name='orgatn',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.organization'),
        ),
        migrations.AlterField(
            model_name='content',
            name='created',
            field=models.DateTimeField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='updated',
            field=models.DateTimeField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='content_images',
            name='created',
            field=models.DateTimeField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='content_images',
            name='weight',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
