# Generated by Django 4.1.3 on 2023-01-16 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0009_alter_city_lattitude_alter_city_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='destination_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=50)),
                ('description', models.CharField(blank=True, default=None, max_length=200)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
