# Generated by Django 4.1.3 on 2023-01-31 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0009_organization_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinstions',
            name='destn_type',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
