# Generated by Django 4.1.3 on 2023-01-17 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0009_booking_type_content_coupon_coupon_type_customer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='created',
            field=models.DateTimeField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='updated',
            field=models.DateTimeField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='content_images',
            name='created',
            field=models.DateTimeField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='content_images',
            name='weight',
            field=models.IntegerField(blank=True, max_length=200, null=True),
        ),
    ]
