# Generated by Django 4.1.3 on 2023-01-31 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0011_alter_destinstions_destn_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='best_things',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('img', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='staff_department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='customer_auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens', models.CharField(default='', max_length=100)),
                ('username', models.CharField(default='', max_length=50)),
                ('u_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.customer')),
            ],
        ),
    ]
