# Generated by Django 4.1.3 on 2023-01-17 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0011_alter_content_created_alter_content_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='c_type',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='usage_limit',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='used_by',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='weight',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
