# Generated by Django 4.1.3 on 2023-01-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0010_alter_content_created_alter_content_updated_and_more'),
        ('dot_app', '0012_alter_coupon_c_type_alter_coupon_usage_limit_and_more'),
    ]

    operations = [
    ]
