# Generated by Django 4.1.3 on 2023-01-31 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0012_alter_destn_facility_destinstions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facility_image',
            name='destinstion',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
