# Generated by Django 4.1.3 on 2023-01-31 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0013_alter_content_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinstions',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=200),
        ),
    ]
