# Generated by Django 4.1.3 on 2023-01-17 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0015_userprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination_area',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='destination_area',
            name='state',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
