# Generated by Django 4.1.3 on 2023-02-01 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0015_userprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='destn_facility',
            name='c_user',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AddField(
            model_name='facility_image',
            name='c_user',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
