# Generated by Django 4.1.3 on 2023-01-17 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0015_userprofile_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contact_person',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='hotel_type',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
