# Generated by Django 4.1.3 on 2023-02-01 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0015_alter_destinstions_climate_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('img', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
