# Generated by Django 4.1.3 on 2023-02-01 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0016_destn_facility_c_user_facility_image_c_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='c_user',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
