# Generated by Django 4.1.3 on 2023-01-18 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0016_destination_area_country_destination_area_state'),
        ('dot_app', '0016_userprofile_contact_person_userprofile_hotel_type'),
    ]

    operations = [
    ]
