# Generated by Django 4.1.3 on 2023-02-02 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0017_destination_area_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination_area',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=200),
        ),
    ]
