# Generated by Django 4.1.3 on 2023-02-03 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0017_userprofile_c_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('feedback', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='faq_category',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='faq_category',
            name='popularity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
