# Generated by Django 4.1.3 on 2023-01-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0017_merge_20230118_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinstions',
            name='culture',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
