# Generated by Django 4.1.3 on 2023-02-03 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0018_destination_area_description'),
        ('dot_app', '0018_feedback_alter_faq_category_name_and_more'),
    ]

    operations = [
    ]
