# Generated by Django 4.1.3 on 2023-01-18 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0018_alter_destinstions_culture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destinstions',
            name='culture',
            field=models.TextField(),
        ),
    ]
