# Generated by Django 4.1.3 on 2023-02-03 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0019_merge_20230203_1227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='img',
        ),
    ]
