# Generated by Django 4.1.3 on 2023-02-07 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0019_merge_20230203_1227'),
    ]

    operations = [
        migrations.CreateModel(
            name='icons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('img', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
