# Generated by Django 4.1.3 on 2023-02-03 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0020_remove_card_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='img',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
