# Generated by Django 4.1.3 on 2023-01-19 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0022_merge_0020_hotel_type_0021_alter_destinstions_culture'),
    ]

    operations = [
        migrations.DeleteModel(
            name='hotel_type',
        ),
    ]
