# Generated by Django 4.1.3 on 2023-01-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0022_merge_0020_hotel_type_0021_alter_destinstions_culture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='pwd',
            new_name='password',
        ),
        migrations.AddField(
            model_name='customer',
            name='password2',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
