# Generated by Django 4.1.3 on 2023-02-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0022_alter_content_images_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='access_count',
            field=models.CharField(blank=True, default=0, max_length=200, null=True),
        ),
    ]
