# Generated by Django 4.1.3 on 2023-01-19 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0023_rename_pwd_customer_password_customer_password2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='username',
        ),
    ]
