# Generated by Django 4.1.3 on 2023-02-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0025_alter_faq_dislike_alter_faq_likes'),
    ]

    operations = [
        migrations.CreateModel(
            name='destinationarea_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=200)),
            ],
        ),
    ]
