# Generated by Django 4.1.3 on 2023-01-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0025_destination_area_c_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination_area',
            name='c_user',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
