# Generated by Django 4.1.3 on 2023-01-19 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0026_alter_destination_area_c_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='destinstions',
            name='c_user',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
