# Generated by Django 4.1.3 on 2023-02-14 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0027_content_created_id_content_images_created_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='destinationarea_type',
            new_name='destarea_type',
        ),
    ]
