# Generated by Django 4.1.3 on 2023-01-20 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0027_destinstions_c_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=200),
        ),
    ]
