# Generated by Django 4.1.3 on 2023-01-20 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0024_rename_name_customer_username'),
        ('dot_app', '0027_destinstions_c_user'),
    ]

    operations = [
    ]
