# Generated by Django 4.1.3 on 2023-01-20 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0028_merge_20230120_1030'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cust_profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='cust_profile',
            name='phone',
        ),
    ]
