# Generated by Django 4.1.3 on 2023-02-14 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0028_rename_destinationarea_type_destarea_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='destinationarea_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destnarea', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.destination_area')),
                ('destnarea_type', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.destarea_type')),
            ],
        ),
    ]
