# Generated by Django 4.1.3 on 2023-02-15 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0022_booking_guests'),
        ('dot_app', '0029_destinationarea_type'),
    ]

    operations = [
    ]
