# Generated by Django 4.1.3 on 2023-01-23 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0028_userprofile_name'),
        ('dot_app', '0029_remove_cust_profile_email_remove_cust_profile_phone'),
    ]

    operations = [
    ]
