# Generated by Django 4.1.3 on 2023-01-23 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0030_merge_20230123_1034'),
    ]

    operations = [
        migrations.CreateModel(
            name='staff_department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
    ]
