# Generated by Django 4.1.3 on 2023-01-24 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0031_staff_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer_auth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tokens', models.CharField(default='', max_length=100)),
                ('username', models.CharField(default='', max_length=50)),
                ('u_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.customer')),
            ],
        ),
    ]
