# Generated by Django 4.1.3 on 2023-02-15 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0032_customer_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
