# Generated by Django 4.1.3 on 2023-02-16 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0033_customer_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
    ]
