# Generated by Django 4.1.3 on 2023-02-21 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0032_alter_booking_status'),
        ('dot_app', '0036_memories_alter_destination_review_destinstion_id_and_more'),
    ]

    operations = [
    ]
