# Generated by Django 4.1.3 on 2023-02-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0036_memories_alter_destination_review_destinstion_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memories',
            name='visited_date',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
