# Generated by Django 4.1.3 on 2023-02-21 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0037_alter_memories_visited_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memories',
            old_name='destinstions',
            new_name='destinstion',
        ),
    ]
