# Generated by Django 4.1.3 on 2023-02-21 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0038_alter_booking_guests_alter_booking_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='created_id',
            new_name='c_user',
        ),
        migrations.RenameField(
            model_name='content_images',
            old_name='created_id',
            new_name='c_user',
        ),
    ]
