# Generated by Django 4.1.3 on 2023-02-22 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0039_rename_created_id_content_c_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(blank=True, default='pending', max_length=50, null=True),
        ),
    ]
