# Generated by Django 4.1.3 on 2023-02-23 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0038_rename_destinstions_memories_destinstion'),
        ('dot_app', '0040_alter_booking_status'),
    ]

    operations = [
    ]
