# Generated by Django 4.1.3 on 2023-02-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0042_remove_subscription_subscription_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='memories',
            name='organzn',
            field=models.CharField(blank=True, default=0, max_length=100, null=True),
        ),
    ]
