# Generated by Django 4.1.3 on 2023-03-09 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dot_app', '0043_memories_organzn'),
    ]

    operations = [
        migrations.CreateModel(
            name='organization_Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_id', models.CharField(blank=True, default=0, max_length=100, null=True)),
                ('rating', models.IntegerField(blank=True, null=True)),
                ('review', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.CharField(blank=True, default=0, max_length=100, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('updated', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('cust_id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='dot_app.customer')),
            ],
        ),
    ]
